### ISSUE TITLE
__construct() expects parameter 1 to be string

### ISSUE THREAD

**Issue by Gogowitsch** [dhimelick/osticket-plugin-statusautochange#1]
I believe this happens in cron since I activated the osticket-plugin-statusautochange plugin.

PHP 7.2.24  
osTicket v1.14.1  
````
PHP Fatal error:  Uncaught TypeError: DateTime::__construct() expects parameter 1 to be string, object given in /include/class.ticket.php:541
Stack trace:
#0 /include/class.ticket.php(541): DateTime->__construct(Object(SqlFunction), Object(DateTimeZone))
#1 /include/class.ticket.php(553): Ticket->getSLADueDate(true)
#2 /include/class.ticket.php(1526): Ticket->updateEstDueDate()
#3 /include/class.ticket.php(1560): Ticket->{closure}(Object(Ticket))
#4 /include/class.ticket.php(1606): Ticket->setStatus(Object(TicketStatus))
#5 /include/class.ticket.php(1865): Ticket->reopen()
#6 /include/class.ticket.php(3103): Ticket->onMessage(Object(MessageThreadEntry), true, true)
#7 /include/class.ticket.php(3484): Ticket->postMessa in /include/class.ticket.php on line 541
````

**Comment by dhimelick** [comment]
Nothing in this plugin directly deals with dates or SLAs, but when a ticket gets reopened, osT updates the due date based on the SLA. This is normal osT behavior that should happen on any ticket reopening, not just with this plugin, so my best guess is that you've got a problem between your osT and PHP versions.

@fonata I realize it's been awhile since you opened this issue. Are you sure this only happens with this plugin installed? Does it still happen with an updated version of osT and/or PHP?
