### ISSUE TITLE
Requirement to change status

### ISSUE THREAD

**Issue by Phil-GER** [dhimelick/osticket-plugin-statusautochange#4]
Is it possible to implement a Condition that must be true before the Status can be changed? 

What I want to do:

We have a "awaiting response" Status and only if the Ticket has this Specific Status it should change the Status to "responded". 

Can we do that? Thanks.

**Comment by dhimelick** [comment]
I realize it's been awhile since this issue was submitted, but the [latest release](https://github.com/dhimelick/osticket-plugin-statusautochange/releases/tag/v2.1.0) adds this feature with an "any" status default option to preserve the current standard behavior of changing status for any customer reply. Hope that works for your needs!
